'use client'

import { useState } from 'react'
import { legacyReduxStore } from '@/features/redux-legacy/infrastructure/store'
import { reduxToolkitStore } from '@/features/redux-toolkit/infrastructure/store'
import { incrementCounter, decrementCounter, resetCounter } from '@/features/redux-legacy/presentation/store/actions'
import { toolkitCounterActions } from '@/features/redux-toolkit/presentation/store/slices'

interface DebugLog {
  timestamp: number
  store: 'legacy' | 'toolkit'
  phase: string
  data: any
}

interface StoreAnalysis {
  storeType: string
  actionCreatorType: string
  stateStructure: string
  reducerType: string
  middlewareChain: string[]
  subscriberCount: number
  dispatchMechanism: string
  stateUpdateMethod: string
}

export function DebugStore() {
  const [logs, setLogs] = useState<DebugLog[]>([])
  const [comparisonMode, setComparisonMode] = useState(false)
  const [showStructure, setShowStructure] = useState(false)

  const addLog = (store: 'legacy' | 'toolkit', phase: string, data: any) => {
    setLogs(prev => [...prev, { timestamp: Date.now(), store, phase, data }])
  }

  const clearLogs = () => {
    setLogs([])
    console.clear()
  }

  const analyzeStore = (store: any, storeName: string): StoreAnalysis => {
    const state = store.getState()
    
    // Determine store type
    const storeType = storeName === 'legacy' ? 'legacy_createStore (Classic Redux)' : 'configureStore (Redux Toolkit with Immer)'
    
    // Analyze middleware
    const middlewareChain = storeName === 'legacy' 
      ? ['redux-thunk (default)', 'timelineMiddleware (custom)']
      : ['thunk', '@reduxjs/toolkit middleware', 'immer middleware']
    
    // Get subscriber count by attempting unsubscribe
    let subscriberCount = 0
    try {
      const unsub = store.subscribe(() => {})
      subscriberCount = 1 // At least one
      unsub()
    } catch (e) {
      subscriberCount = 0
    }

    return {
      storeType,
      actionCreatorType: storeName === 'legacy' ? 'Manual action creators (functions returning action objects)' : 'createSlice generators (autogenerated from reducers)',
      stateStructure: JSON.stringify(state, null, 2).split('\n').length + ' lines',
      reducerType: storeName === 'legacy' ? 'Manually combined reducers with explicit switch statements' : 'Immer-enhanced reducers (builder pattern)',
      middlewareChain,
      subscriberCount,
      dispatchMechanism: storeName === 'legacy' ? 'Raw dispatch(action) -> middleware chain -> reducer' : 'Enhanced dispatch with thunk + Immer drafts',
      stateUpdateMethod: storeName === 'legacy' ? 'Manual object spread (...state)' : 'Immer proxy (mutate-like syntax)',
    }
  }

  const getActionDetails = (store: any, storeName: string, actionType: 'increment' | 'decrement' | 'reset') => {
    let action
    
    if (storeName === 'legacy') {
      switch (actionType) {
        case 'increment':
          action = incrementCounter()
          break
        case 'decrement':
          action = decrementCounter()
          break
        case 'reset':
          action = resetCounter()
          break
      }
    } else {
      switch (actionType) {
        case 'increment':
          action = toolkitCounterActions.increment()
          break
        case 'decrement':
          action = toolkitCounterActions.decrement()
          break
        case 'reset':
          action = toolkitCounterActions.reset()
          break
      }
    }

    return {
      action,
      creator: storeName === 'legacy' 
        ? `${actionType}Counter() - manual factory function`
        : `${actionType}() - generated by createSlice`,
      hasPayload: action.payload !== undefined,
      payloadStructure: action.payload ? typeof action.payload === 'object' ? JSON.stringify(action.payload) : action.payload : 'undefined',
    }
  }

  const testLegacy = (actionType: 'increment' | 'decrement' | 'reset') => {
    console.log(`\n${'═'.repeat(80)}`)
    console.log('🏛️  REDUX LEGACY (Classic Redux)')
    console.log('═'.repeat(80))

    // Store Analysis
    const storeAnalysis = analyzeStore(legacyReduxStore, 'legacy')
    console.group('📦 Store Configuration')
    console.log('Store Type:', storeAnalysis.storeType)
    console.log('Created with:', 'legacy_createStore + combineReducers')
    console.log('Middleware Chain:', storeAnalysis.middlewareChain)
    console.log('Active Subscribers:', storeAnalysis.subscriberCount)
    console.groupEnd()

    // Initial State
    const initialState = legacyReduxStore.getState()
    addLog('legacy', 'initial-state', initialState)
    console.group('📊 Initial State')
    console.log('Full State Object:', JSON.stringify(initialState, null, 2))
    console.log('Counter Value:', initialState.counter?.value)
    console.log('Timeline Length:', initialState.timeline?.actions?.length || 0)
    console.log('Last 3 Actions in Timeline:', initialState.timeline?.actions?.slice(-3) || [])
    console.groupEnd()

    // Action Details
    const actionDetails = getActionDetails(legacyReduxStore, 'legacy', actionType)
    addLog('legacy', 'action', actionDetails.action)
    console.group('📤 Action (Raw Object)')
    console.log('Action Creator:', actionDetails.creator)
    console.log('Full Action:', JSON.stringify(actionDetails.action, null, 2))
    console.log('Type:', actionDetails.action.type)
    console.log('Has Payload:', actionDetails.hasPayload)
    if (actionDetails.hasPayload) {
      console.log('Payload:', actionDetails.payloadStructure)
    }
    console.groupEnd()

    // Reducer Execution
    console.group('⚙️  Reducer Execution Flow')
    console.log('Reducer Pattern: Manual switch statement')
    console.log('Switch cases: INCREMENT_COUNTER, DECREMENT_COUNTER, RESET_COUNTER, default')
    console.log('State Update Pattern: { ...state, value: state.value ± 1 }')
    console.log('New object created: Yes (manual spread operator)')
    console.groupEnd()

    // Middleware Execution
    console.group('🔗 Middleware Chain Execution')
    console.log('1. redux-thunk (default middleware)')
    console.log('   - Checks if action is function, dispatches if normal action object')
    console.log('2. timelineMiddleware (custom middleware)')
    console.log('   - Intercepts all actions')
    console.log('   - Records action type and timestamp')
    console.log('   - Appends to timeline.actions array')
    console.groupEnd()

    // Dispatch
    const startTime = performance.now()
    const dispatchResult = legacyReduxStore.dispatch(actionDetails.action)
    const endTime = performance.now()
    addLog('legacy', 'dispatch-result', dispatchResult)
    console.group('✅ Dispatch Execution')
    console.log('Dispatch Result:', JSON.stringify(dispatchResult, null, 2))
    console.log('Execution Time:', `${(endTime - startTime).toFixed(3)}ms`)
    console.log('Result is same action object:', dispatchResult === actionDetails.action)
    console.groupEnd()

    // New State
    const newState = legacyReduxStore.getState()
    addLog('legacy', 'new-state', newState)
    console.group('📊 New State After Dispatch')
    console.log('Full State Object:', JSON.stringify(newState, null, 2))
    console.log('Counter Value Changed:', initialState.counter?.value, '→', newState.counter?.value)
    console.log('Timeline Updated:', initialState.timeline?.actions?.length, '→', newState.timeline?.actions?.length)
    console.log('Last Action in Timeline:', newState.timeline?.actions?.[newState.timeline.actions.length - 1] || 'none')
    console.groupEnd()

    // State Reference
    console.group('🔍 State Reference Tracking')
    console.log('New root state === old root state:', newState === initialState)
    console.log('New counter === old counter:', newState.counter === initialState.counter)
    console.log('New timeline === old timeline:', newState.timeline === initialState.timeline)
    console.log('Counter object recreated:', newState.counter !== initialState.counter)
    console.log('Timeline array replaced:', newState.timeline.actions !== initialState.timeline?.actions)
    console.groupEnd()

    return { initialState, action: actionDetails.action, newState, executionTime: endTime - startTime }
  }

  const testToolkit = (actionType: 'increment' | 'decrement' | 'reset') => {
    console.log(`\n${'═'.repeat(80)}`)
    console.log('⚡ REDUX TOOLKIT (Modern Redux)')
    console.log('═'.repeat(80))

    // Store Analysis
    const storeAnalysis = analyzeStore(reduxToolkitStore, 'toolkit')
    console.group('📦 Store Configuration')
    console.log('Store Type:', storeAnalysis.storeType)
    console.log('Created with:', 'configureStore() from @reduxjs/toolkit')
    console.log('Middleware Chain:', storeAnalysis.middlewareChain)
    console.log('Immer Enabled:', true)
    console.log('Redux DevTools Enabled:', true)
    console.log('Active Subscribers:', storeAnalysis.subscriberCount)
    console.groupEnd()

    // Initial State
    const initialState = reduxToolkitStore.getState()
    addLog('toolkit', 'initial-state', initialState)
    console.group('📊 Initial State')
    console.log('Full State Object:', JSON.stringify(initialState, null, 2))
    console.log('Counter Value:', initialState.counter?.value)
    console.log('Timeline Length:', initialState.timeline?.actions?.length || 0)
    console.log('Last 3 Actions in Timeline:', initialState.timeline?.actions?.slice(-3) || [])
    console.groupEnd()

    // Action Details
    const actionDetails = getActionDetails(reduxToolkitStore, 'toolkit', actionType)
    addLog('toolkit', 'action', actionDetails.action)
    console.group('📤 Action (Generated by createSlice)')
    console.log('Action Creator:', actionDetails.creator)
    console.log('Full Action:', JSON.stringify(actionDetails.action, null, 2))
    console.log('Type:', actionDetails.action.type)
    console.log('Type Pattern:', 'counterSlice/[action] (namespace/action)')
    console.log('Has Payload:', actionDetails.hasPayload)
    if (actionDetails.hasPayload) {
      console.log('Payload:', actionDetails.payloadStructure)
    }
    console.log('_type symbol:', actionDetails.action._type || 'none (not a PayloadAction)')
    console.groupEnd()

    // Reducer Execution with Immer
    console.group('⚙️  Reducer Execution Flow (with Immer)')
    console.log('Reducer Pattern: Builder pattern from createSlice')
    console.log('Cases: increment, decrement, reset')
    console.log('State Update Pattern: state.value += 1 (Immer mutative syntax)')
    console.log('Immer Processing:')
    console.log('  1. Creates draft proxy around state')
    console.log('  2. Tracks mutations to draft')
    console.log('  3. Produces new immutable state from mutations')
    console.log('  4. Original state never touched')
    console.groupEnd()

    // Middleware Execution
    console.group('🔗 Middleware Chain Execution')
    console.log('1. redux-thunk (included by default)')
    console.log('   - Checks if action is function, dispatches if normal action object')
    console.log('2. Immer middleware')
    console.log('   - Enables frozen state in dev mode')
    console.log('   - Freezes state to prevent mutations')
    console.log('3. Redux DevTools middleware')
    console.log('   - Time-travel debugging')
    console.log('   - Action history')
    console.log('4. Custom timeline middleware (if added)')
    console.log('   - Records actions like Legacy does')
    console.groupEnd()

    // Dispatch
    const startTime = performance.now()
    const dispatchResult = reduxToolkitStore.dispatch(actionDetails.action)
    const endTime = performance.now()
    addLog('toolkit', 'dispatch-result', dispatchResult)
    console.group('✅ Dispatch Execution')
    console.log('Dispatch Result:', JSON.stringify(dispatchResult, null, 2))
    console.log('Execution Time:', `${(endTime - startTime).toFixed(3)}ms`)
    console.log('Result is same action object:', dispatchResult === actionDetails.action)
    console.groupEnd()

    // New State
    const newState = reduxToolkitStore.getState()
    addLog('toolkit', 'new-state', newState)
    console.group('📊 New State After Dispatch')
    console.log('Full State Object:', JSON.stringify(newState, null, 2))
    console.log('Counter Value Changed:', initialState.counter?.value, '→', newState.counter?.value)
    console.log('Timeline Updated:', initialState.timeline?.actions?.length, '→', newState.timeline?.actions?.length)
    console.log('Last Action in Timeline:', newState.timeline?.actions?.[newState.timeline.actions.length - 1] || 'none')
    console.groupEnd()

    // State Reference
    console.group('🔍 State Reference Tracking')
    console.log('New root state === old root state:', newState === initialState)
    console.log('New counter === old counter:', newState.counter === initialState.counter)
    console.log('New timeline === old timeline:', newState.timeline === initialState.timeline)
    console.log('Counter object recreated:', newState.counter !== initialState.counter)
    console.log('Timeline array replaced:', newState.timeline.actions !== initialState.timeline?.actions)
    console.log('Object frozen (dev mode):', Object.isFrozen(newState))
    console.groupEnd()

    return { initialState, action: actionDetails.action, newState, executionTime: endTime - startTime }
  }

  const handleTestAction = (actionType: 'increment' | 'decrement' | 'reset') => {
    if (comparisonMode) {
      const legacy = testLegacy(actionType)
      const toolkit = testToolkit(actionType)
      printComparison(legacy, toolkit)
    } else {
      testLegacy(actionType)
      testToolkit(actionType)
    }
  }

  const printComparison = (legacy: any, toolkit: any) => {
    console.log(`\n${'═'.repeat(80)}`)
    console.log('🔬 DETAILED COMPARISON: Legacy vs Toolkit')
    console.log('═'.repeat(80))

    console.group('📤 Action Structure')
    console.log('Legacy Action:', JSON.stringify(legacy.action, null, 2))
    console.log('Toolkit Action:', JSON.stringify(toolkit.action, null, 2))
    console.log('Action structures identical:', JSON.stringify(legacy.action) === JSON.stringify(toolkit.action))
    console.groupEnd()

    console.group('📊 State Structure')
    console.log('Legacy State:', JSON.stringify(legacy.newState, null, 2))
    console.log('Toolkit State:', JSON.stringify(toolkit.newState, null, 2))
    console.log('State structures identical:', JSON.stringify(legacy.newState) === JSON.stringify(toolkit.newState))
    console.groupEnd()

    console.group('⚡ Performance')
    console.log('Legacy Execution Time:', legacy.executionTime.toFixed(3) + 'ms')
    console.log('Toolkit Execution Time:', toolkit.executionTime.toFixed(3) + 'ms')
    console.log('Faster:', legacy.executionTime < toolkit.executionTime ? 'Legacy' : 'Toolkit')
    console.groupEnd()

    console.group('✅ Counter Values')
    console.log('Legacy:', legacy.newState.counter?.value)
    console.log('Toolkit:', toolkit.newState.counter?.value)
    console.log('Match:', legacy.newState.counter?.value === toolkit.newState.counter?.value)
    console.groupEnd()

    console.group('📝 Timeline/History')
    console.log('Legacy Timeline Actions:', legacy.newState.timeline?.actions?.length)
    console.log('Toolkit Timeline Actions:', toolkit.newState.timeline?.actions?.length)
    console.log('Histories Synchronized:', legacy.newState.timeline?.actions?.length === toolkit.newState.timeline?.actions?.length)
    console.groupEnd()

    console.group('🎯 Key Differences')
    console.log('1. Action Creators:')
    console.log('   - Legacy: Manual functions that return action objects')
    console.log('   - Toolkit: Auto-generated by createSlice from reducer definition')
    console.log('')
    console.log('2. State Updates:')
    console.log('   - Legacy: Manual immutable updates ({ ...state, value: ... })')
    console.log('   - Toolkit: Immer-enabled (looks mutable but is immutable)')
    console.log('')
    console.log('3. Middleware:')
    console.log('   - Legacy: Only what you configure (default + timelineMiddleware)')
    console.log('   - Toolkit: Auto-configured (thunk, immer, devtools)')
    console.log('')
    console.log('4. Type Safety:')
    console.log('   - Legacy: Manual typing required')
    console.log('   - Toolkit: Auto-generated from builder pattern')
    console.groupEnd()
  }

  return (
    <div className="border-2 border-purple-500 p-4 my-4 bg-purple-50 rounded">
      <div className="flex items-center justify-between mb-3">
        <h3 className="font-bold text-purple-700">🔬 DEEP DEBUG PANEL - Complete Flow Analysis</h3>
        <div className="flex items-center gap-4">
          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={comparisonMode}
              onChange={(e) => setComparisonMode(e.target.checked)}
              className="w-4 h-4"
            />
            <span className="text-purple-700">Comparison Mode</span>
          </label>
          <label className="flex items-center gap-2 text-sm">
            <input
              type="checkbox"
              checked={showStructure}
              onChange={(e) => setShowStructure(e.target.checked)}
              className="w-4 h-4"
            />
            <span className="text-purple-700">Show Store Info</span>
          </label>
        </div>
      </div>

      {showStructure && (
        <div className="bg-white border border-purple-200 rounded p-3 mb-3 text-xs space-y-2">
          <div className="grid grid-cols-2 gap-4">
            <div className="bg-red-50 p-2 rounded">
              <h4 className="font-bold text-red-700 mb-1">Redux Legacy</h4>
              <p className="text-gray-700"><strong>Store:</strong> legacy_createStore</p>
              <p className="text-gray-700"><strong>Reducer:</strong> Manual combineReducers</p>
              <p className="text-gray-700"><strong>Actions:</strong> Manual factory functions</p>
              <p className="text-gray-700"><strong>State Updates:</strong> Manual spread operator</p>
              <p className="text-gray-700"><strong>Middleware:</strong> thunk + timelineMiddleware</p>
            </div>
            <div className="bg-blue-50 p-2 rounded">
              <h4 className="font-bold text-blue-700 mb-1">Redux Toolkit</h4>
              <p className="text-gray-700"><strong>Store:</strong> configureStore</p>
              <p className="text-gray-700"><strong>Reducer:</strong> createSlice with builders</p>
              <p className="text-gray-700"><strong>Actions:</strong> Auto-generated</p>
              <p className="text-gray-700"><strong>State Updates:</strong> Immer drafts</p>
              <p className="text-gray-700"><strong>Middleware:</strong> Auto-configured + devtools</p>
            </div>
          </div>
        </div>
      )}

      <div className="space-y-2 mb-3">
        <div className="flex gap-2 flex-wrap">
          <button
            onClick={() => handleTestAction('increment')}
            className="bg-green-500 text-white px-3 py-2 text-sm font-medium rounded hover:bg-green-600 transition"
          >
            ➕ Increment
          </button>
          <button
            onClick={() => handleTestAction('decrement')}
            className="bg-orange-500 text-white px-3 py-2 text-sm font-medium rounded hover:bg-orange-600 transition"
          >
            ➖ Decrement
          </button>
          <button
            onClick={() => handleTestAction('reset')}
            className="bg-red-500 text-white px-3 py-2 text-sm font-medium rounded hover:bg-red-600 transition"
          >
            🔄 Reset
          </button>
          <button
            onClick={clearLogs}
            className="bg-gray-500 text-white px-3 py-2 text-sm font-medium rounded hover:bg-gray-600 transition ml-auto"
          >
            Clear Logs
          </button>
        </div>
        <p className="text-xs text-purple-700">
          💡 <strong>📖 Full Analysis:</strong> Open browser console (F12) to see complete execution details including:<br/>
          • Store configuration and middleware chain • Initial state structure • Action creator types and payloads<br/>
          • Reducer execution patterns (manual vs Immer) • Middleware execution flow • Reference tracking (state immutability verification)<br/>
          • Performance metrics • Detailed comparison between Legacy and Toolkit
        </p>
      </div>

      {logs.length > 0 && (
        <div className="bg-white border border-purple-200 rounded p-3 text-xs max-h-80 overflow-y-auto">
          <h4 className="font-bold mb-2 text-purple-700">Event Log</h4>
          <div className="font-mono space-y-1">
            {logs.map((log, idx) => (
              <div key={idx} className={`flex gap-2 pb-1 ${idx > 0 && logs[idx - 1].store !== log.store ? 'border-t pt-1' : ''} ${log.store === 'legacy' ? 'text-red-600' : 'text-blue-600'}`}>
                <span className="font-bold w-6">[{idx}]</span>
                <span className="w-12 font-bold">{log.store === 'legacy' ? '🏛️ ' : '⚡'}</span>
                <span className="w-32 font-bold text-gray-600">{log.phase}</span>
                <span className="flex-1 truncate">{typeof log.data === 'object' ? JSON.stringify(log.data).substring(0, 100) : String(log.data).substring(0, 100)}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}
