'use client'

interface ActionAnalysisPanelProps {
  lastAction: any | null
  storeName: 'legacy' | 'toolkit'
}

export function ActionAnalysisPanel({ lastAction, storeName }: ActionAnalysisPanelProps) {
  if (!lastAction) {
    return (
      <div className="rounded-lg border border-zinc-700 bg-zinc-900 p-4">
        <h3 className="text-sm font-semibold text-zinc-300 mb-2">📤 Last Action</h3>
        <p className="text-xs text-zinc-500">Dispatch an action to see details</p>
      </div>
    )
  }

  const isLegacy = storeName === 'legacy'

  return (
    <div className="rounded-lg border border-zinc-700 bg-zinc-900 p-4 space-y-3">
      <h3 className="text-sm font-semibold text-zinc-300">📤 Last Action Analysis</h3>

      {/* Action Type */}
      <div className="bg-zinc-950 p-3 rounded border border-zinc-800">
        <h4 className="text-xs font-semibold text-zinc-400 mb-1">Type</h4>
        <p className="text-xs font-mono text-blue-400">{lastAction.type}</p>
        {isLegacy ? (
          <p className="text-xs text-zinc-500 mt-1">Plain string constant</p>
        ) : (
          <p className="text-xs text-zinc-500 mt-1">Namespaced: {"sliceName/actionName"}</p>
        )}
      </div>

      {/* Payload */}
      {lastAction.payload !== undefined && (
        <div className="bg-zinc-950 p-3 rounded border border-zinc-800">
          <h4 className="text-xs font-semibold text-zinc-400 mb-1">Payload</h4>
          <p className="text-xs font-mono text-green-400 overflow-auto max-h-16">
            {JSON.stringify(lastAction.payload, null, 2)}
          </p>
        </div>
      )}

      {/* Full Action Object */}
      <div className="bg-zinc-950 p-3 rounded border border-zinc-800">
        <h4 className="text-xs font-semibold text-zinc-400 mb-1">Full Object</h4>
        <pre className="text-xs text-zinc-400 overflow-auto max-h-24 font-mono">
          {JSON.stringify(lastAction, null, 2)}
        </pre>
      </div>

      {/* Creator Info */}
      <div className="bg-zinc-950 p-3 rounded border border-zinc-800">
        <h4 className="text-xs font-semibold text-zinc-400 mb-1">Creator Pattern</h4>
        {isLegacy ? (
          <p className="text-xs text-zinc-500">
            ✏️ <span className="text-yellow-400">Manual Action Creator</span>
            <br/>
            <code className="text-xs font-mono text-zinc-400">
              {'function increment() {'}
              <br/>
              {'  return { type: "INCREMENT_COUNTER" }'}
              <br/>
              {'}'}
            </code>
          </p>
        ) : (
          <p className="text-xs text-zinc-500">
            🤖 <span className="text-green-400">Auto-Generated by createSlice</span>
            <br/>
            <code className="text-xs font-mono text-zinc-400">
              {'createSlice({'}
              <br/>
              {'  reducers: { increment: (state) => { ... } }'}
              <br/>
              {'}).actions.increment'}
            </code>
          </p>
        )}
      </div>
    </div>
  )
}
