'use client'

interface DifferencesItem {
  category: string
  legacy: string
  toolkit: string
}

export function ComparisonDifferences() {
  const differences: DifferencesItem[] = [
    {
      category: '🏪 Store Creation',
      legacy: 'legacy_createStore(reducer, middleware)',
      toolkit: 'configureStore({ reducer, middleware })',
    },
    {
      category: '📦 Reducer Combination',
      legacy: 'combineReducers({ counter, timeline })',
      toolkit: 'Built-in reducer combination',
    },
    {
      category: '📤 Action Creators',
      legacy: 'Manual functions returning action objects',
      toolkit: 'Auto-generated by createSlice',
    },
    {
      category: '⚙️ Reducer Pattern',
      legacy: 'switch(action.type) { case A: ... }',
      toolkit: 'builder.addCase(action, (state) => {})',
    },
    {
      category: '📝 State Updates',
      legacy: '{ ...state, field: value } (manual)',
      toolkit: 'state.field = value (Immer drafts)',
    },
    {
      category: '🔗 Middleware',
      legacy: 'Manual middleware configuration',
      toolkit: 'Auto-configured (thunk, immer, devtools)',
    },
    {
      category: '🎯 Type Safety',
      legacy: 'Manual typing required',
      toolkit: 'Auto-generated types from builder',
    },
    {
      category: '❄️ Immutability',
      legacy: 'Manual object spread',
      toolkit: 'Immer ensures immutability',
    },
    {
      category: '🐛 DevTools',
      legacy: 'Manual setup required',
      toolkit: 'Auto-integrated',
    },
    {
      category: '📊 Action Types',
      legacy: 'String constants (INCREMENT)',
      toolkit: 'Namespaced types (counter/increment)',
    },
    {
      category: '🔄 Async Operations',
      legacy: 'Custom middleware needed',
      toolkit: 'createAsyncThunk built-in',
    },
    {
      category: '⚡ Bundle Size',
      legacy: 'Minimal (~2kb)',
      toolkit: 'With dependencies (~15kb)',
    },
  ]

  return (
    <div className="bg-gradient-to-b from-purple-50 to-pink-50 rounded-lg border-2 border-purple-200 p-6">
      <h3 className="text-center text-lg font-bold text-purple-900 mb-6">
        🔍 Implementation Differences
      </h3>

      <div className="space-y-3">
        {differences.map((item, idx) => (
          <div
            key={idx}
            className="bg-white rounded border border-purple-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow"
          >
            <div className="bg-gradient-to-r from-purple-100 to-pink-100 px-4 py-2 border-b border-purple-200">
              <h4 className="font-semibold text-purple-900 text-sm">{item.category}</h4>
            </div>

            <div className="grid grid-cols-2 divide-x divide-purple-200">
              {/* Legacy */}
              <div className="p-3 bg-gradient-to-br from-red-50 to-red-25">
                <p className="text-xs font-semibold text-red-700 mb-1">🏛️ Redux Legacy</p>
                <p className="text-xs text-red-900 font-mono leading-relaxed">{item.legacy}</p>
              </div>

              {/* Toolkit */}
              <div className="p-3 bg-gradient-to-br from-blue-50 to-blue-25">
                <p className="text-xs font-semibold text-blue-700 mb-1">⚡ Redux Toolkit</p>
                <p className="text-xs text-blue-900 font-mono leading-relaxed">{item.toolkit}</p>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* Summary */}
      <div className="mt-6 pt-4 border-t border-purple-200">
        <div className="grid grid-cols-2 gap-4">
          <div className="bg-red-50 rounded p-3 border border-red-200">
            <h4 className="text-xs font-bold text-red-700 mb-2">🏛️ Redux Legacy Strengths</h4>
            <ul className="text-xs text-red-900 space-y-1">
              <li>✓ Minimal dependencies</li>
              <li>✓ Complete control</li>
              <li>✓ Learning friendly</li>
              <li>✓ Explicit patterns</li>
            </ul>
          </div>
          <div className="bg-blue-50 rounded p-3 border border-blue-200">
            <h4 className="text-xs font-bold text-blue-700 mb-2">⚡ Redux Toolkit Strengths</h4>
            <ul className="text-xs text-blue-900 space-y-1">
              <li>✓ Less boilerplate</li>
              <li>✓ Built-in best practices</li>
              <li>✓ Better DX</li>
              <li>✓ Auto-generated utilities</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
